version: '3'
services:
  mysql:
    image: mysql:latest
    hostname: hamster_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    container_name: hamster_mysql
  redis:
    image: redis:latest
    hostname: hamster_redis
    ports:
      - 6379:6379
    command: redis-server --requirepass 123456
    container_name: hamster_redis
  rabbitmq:
    image: rabbitmq:management
    hostname: hamster_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    container_name: hamster_rabbitmq